<?php

declare(strict_types=1);

namespace Waaseyaa\CLI\Handler;

use Waaseyaa\Entity\EntityTypeInterface;
use Waaseyaa\Field\FieldDefinition;

/**
 * Generates the PHP source of an "add translations" migration for a given
 * entity type and primary backend.
 *
 * The generated migration is a single anonymous class with raw-SQL `up()` and
 * `down()` bodies. SQL is executed via {@see \Waaseyaa\Foundation\Migration\SchemaBuilder::getConnection()}
 * so that DBAL handles parameter binding and platform abstraction at apply time.
 *
 * DDL shape (FR-050..FR-053, WP04 sql-blob + WP05 sql-column contracts):
 *
 *   sql-column path
 *     up():
 *       CREATE TABLE {table}_translations (entity_id, langcode, <translatable cols>, PK(entity_id, langcode), FK -> {table})
 *       INSERT INTO {table}_translations SELECT entity_id, '<lc>', <cols> FROM {table}
 *       ALTER TABLE {table} DROP COLUMN <translatable col>...
 *       ALTER TABLE {table} ADD COLUMN default_langcode VARCHAR(12) NOT NULL DEFAULT '<lc>'
 *     down() (DATA LOSS):
 *       backfill primary cols from rows where langcode = default_langcode
 *       DROP TABLE {table}_translations
 *       ALTER TABLE {table} DROP COLUMN default_langcode
 *
 *   sql-blob path
 *     up():
 *       ALTER TABLE {table} ADD COLUMN default_langcode VARCHAR(12) NOT NULL DEFAULT '<lc>'
 *       UPDATE {table} SET langcode = '<lc>' WHERE langcode IS NULL OR langcode = ''
 *       widen PK to (entity_id, langcode) (DBAL handles per-platform rebuild)
 *       partial UNIQUE INDEX on uuid WHERE langcode = default_langcode (with MySQL note)
 *     down() (DATA LOSS):
 *       narrow PK back to (entity_id)
 *       DROP INDEX
 *       ALTER TABLE {table} DROP COLUMN default_langcode
 *
 * @internal
 */
final class AddTranslationsMigrationGenerator
{
    /**
     * Render the PHP source of the generated migration.
     *
     * @param 'sql-blob'|'sql-column' $backend
     * @param list<string>            $translatableColumns Schema-level column names (sql-column path).
     */
    public function render(
        EntityTypeInterface $entityType,
        string $defaultLangcode,
        string $backend,
        array $translatableColumns,
    ): string {
        $table = $this->phpStringLiteral($entityType->id());
        $translationsTable = $this->phpStringLiteral($entityType->id() . '_translations');
        $defaultLc = $this->phpStringLiteral($defaultLangcode);
        $cols = $this->phpArrayLiteral($translatableColumns);

        return <<<PHP
            <?php

            declare(strict_types=1);

            use Waaseyaa\\Foundation\\Migration\\Migration;
            use Waaseyaa\\Foundation\\Migration\\SchemaBuilder;

            /**
             * Promote `{$entityType->id()}` to a translatable entity type.
             *
             * Backend: {$backend}
             * Default langcode: {$defaultLangcode}
             *
             * Generated by `make:migration --add-translations={$entityType->id()} --default-langcode={$defaultLangcode}`.
             */
            return new class extends Migration
            {
                private const TABLE = {$table};
                private const TRANSLATIONS_TABLE = {$translationsTable};
                private const DEFAULT_LANGCODE = {$defaultLc};
                /** @var list<string> */
                private const TRANSLATABLE_COLUMNS = {$cols};
                private const BACKEND = '{$backend}';

                public function up(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    if (self::BACKEND === 'sql-column') {
                        // Build the translations table column list.
                        \$cols = ['entity_id INTEGER NOT NULL', 'langcode VARCHAR(12) NOT NULL'];
                        foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                            \$cols[] = \$conn->quoteIdentifier(\$c) . ' TEXT';
                        }
                        \$cols[] = 'PRIMARY KEY (entity_id, langcode)';

                        \$conn->executeStatement(sprintf(
                            'CREATE TABLE %s (%s, FOREIGN KEY (entity_id) REFERENCES %s(id) ON DELETE CASCADE)',
                            \$conn->quoteIdentifier(self::TRANSLATIONS_TABLE),
                            implode(', ', \$cols),
                            \$conn->quoteIdentifier(self::TABLE),
                        ));

                        if (self::TRANSLATABLE_COLUMNS !== []) {
                            \$qCols = array_map(static fn (string \$c): string => \$conn->quoteIdentifier(\$c), self::TRANSLATABLE_COLUMNS);
                            \$conn->executeStatement(sprintf(
                                'INSERT INTO %s (entity_id, langcode, %s) SELECT id, %s, %s FROM %s',
                                \$conn->quoteIdentifier(self::TRANSLATIONS_TABLE),
                                implode(', ', \$qCols),
                                \$conn->quote(self::DEFAULT_LANGCODE),
                                implode(', ', \$qCols),
                                \$conn->quoteIdentifier(self::TABLE),
                            ));

                            foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                                \$conn->executeStatement(sprintf(
                                    'ALTER TABLE %s DROP COLUMN %s',
                                    \$conn->quoteIdentifier(self::TABLE),
                                    \$conn->quoteIdentifier(\$c),
                                ));
                            }
                        }

                        \$conn->executeStatement(sprintf(
                            "ALTER TABLE %s ADD COLUMN default_langcode VARCHAR(12) NOT NULL DEFAULT %s",
                            \$conn->quoteIdentifier(self::TABLE),
                            \$conn->quote(self::DEFAULT_LANGCODE),
                        ));

                        return;
                    }

                    // sql-blob path.
                    \$conn->executeStatement(sprintf(
                        "ALTER TABLE %s ADD COLUMN default_langcode VARCHAR(12) NOT NULL DEFAULT %s",
                        \$conn->quoteIdentifier(self::TABLE),
                        \$conn->quote(self::DEFAULT_LANGCODE),
                    ));

                    \$conn->executeStatement(sprintf(
                        "UPDATE %s SET langcode = %s WHERE langcode IS NULL OR langcode = ''",
                        \$conn->quoteIdentifier(self::TABLE),
                        \$conn->quote(self::DEFAULT_LANGCODE),
                    ));

                    // Widen PK to (entity_id, langcode). DBAL schema diff is the safe path here;
                    // direct ALTER syntax differs per platform (SQLite rebuilds the table, MySQL
                    // accepts `DROP PRIMARY KEY, ADD PRIMARY KEY ...`, PostgreSQL uses constraint ops).
                    \$platform = \$conn->getDatabasePlatform()->getName();
                    if (\$platform === 'mysql') {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP PRIMARY KEY, ADD PRIMARY KEY (entity_id, langcode)',
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    } elseif (\$platform === 'postgresql') {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP CONSTRAINT %s_pkey',
                            \$conn->quoteIdentifier(self::TABLE),
                            self::TABLE,
                        ));
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s ADD PRIMARY KEY (entity_id, langcode)',
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    }
                    // SQLite: PRIMARY KEY widening is handled by SqlSchemaHandler::sync() on the next boot.

                    // Partial unique index on uuid WHERE langcode = default_langcode.
                    // NOTE: MySQL <8 has no partial indexes. Use full unique index on (uuid, langcode) as a fallback.
                    if (\$platform === 'mysql') {
                        \$conn->executeStatement(sprintf(
                            'CREATE UNIQUE INDEX %s_uuid_default ON %s(uuid, langcode)',
                            self::TABLE,
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    } else {
                        \$conn->executeStatement(sprintf(
                            'CREATE UNIQUE INDEX %s_uuid_default ON %s(uuid) WHERE langcode = default_langcode',
                            self::TABLE,
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    }
                }

                /**
                 * DATA LOSS WARNING: This reversal drops non-default-langcode translation rows.
                 * Backup before applying if multilingual content exists. Any field values whose
                 * langcode differs from the snapshotted default ({$defaultLangcode}) will be lost.
                 */
                public function down(SchemaBuilder \$schema): void
                {
                    \$conn = \$schema->getConnection();

                    if (self::BACKEND === 'sql-column') {
                        // Re-add the translatable columns as TEXT NULL.
                        foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                            \$conn->executeStatement(sprintf(
                                'ALTER TABLE %s ADD COLUMN %s TEXT',
                                \$conn->quoteIdentifier(self::TABLE),
                                \$conn->quoteIdentifier(\$c),
                            ));
                        }

                        // Backfill from translations where langcode = default_langcode.
                        if (self::TRANSLATABLE_COLUMNS !== []) {
                            foreach (self::TRANSLATABLE_COLUMNS as \$c) {
                                \$q = \$conn->quoteIdentifier(\$c);
                                \$conn->executeStatement(sprintf(
                                    'UPDATE %s SET %s = (SELECT %s FROM %s t WHERE t.entity_id = %s.id AND t.langcode = %s)',
                                    \$conn->quoteIdentifier(self::TABLE),
                                    \$q,
                                    \$q,
                                    \$conn->quoteIdentifier(self::TRANSLATIONS_TABLE),
                                    \$conn->quoteIdentifier(self::TABLE),
                                    \$conn->quote(self::DEFAULT_LANGCODE),
                                ));
                            }
                        }

                        \$conn->executeStatement(sprintf(
                            'DROP TABLE %s',
                            \$conn->quoteIdentifier(self::TRANSLATIONS_TABLE),
                        ));

                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP COLUMN default_langcode',
                            \$conn->quoteIdentifier(self::TABLE),
                        ));

                        return;
                    }

                    // sql-blob path.
                    \$platform = \$conn->getDatabasePlatform()->getName();
                    \$conn->executeStatement(sprintf(
                        'DROP INDEX %s_uuid_default',
                        self::TABLE,
                    ));

                    if (\$platform === 'mysql') {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP PRIMARY KEY, ADD PRIMARY KEY (entity_id)',
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    } elseif (\$platform === 'postgresql') {
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s DROP CONSTRAINT %s_pkey',
                            \$conn->quoteIdentifier(self::TABLE),
                            self::TABLE,
                        ));
                        \$conn->executeStatement(sprintf(
                            'ALTER TABLE %s ADD PRIMARY KEY (entity_id)',
                            \$conn->quoteIdentifier(self::TABLE),
                        ));
                    }
                    // SQLite: PK narrowing is handled by SqlSchemaHandler::sync() on the next boot.

                    \$conn->executeStatement(sprintf(
                        'ALTER TABLE %s DROP COLUMN default_langcode',
                        \$conn->quoteIdentifier(self::TABLE),
                    ));
                }
            };

            PHP;
    }

    private function phpStringLiteral(string $value): string
    {
        return "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], $value) . "'";
    }

    /**
     * @param list<string> $values
     */
    private function phpArrayLiteral(array $values): string
    {
        if ($values === []) {
            return '[]';
        }
        $parts = array_map(fn(string $v): string => $this->phpStringLiteral($v), $values);

        return '[' . implode(', ', $parts) . ']';
    }

    /**
     * Walk an entity type's field definitions and return the translatable column names.
     *
     * Used for sql-column generation. For sql-blob the column list is irrelevant
     * (translations live in the row's `_data` JSON blob plus the langcode key).
     *
     * @return list<string>
     */
    public function translatableColumns(EntityTypeInterface $entityType): array
    {
        $cols = [];
        foreach ($entityType->getFieldDefinitions() as $field) {
            if (!$field instanceof FieldDefinition) {
                continue;
            }
            if ($field->isTranslatable()) {
                $cols[] = $field->getName();
            }
        }

        return $cols;
    }
}
